"""create restaurant_schedules

Revision ID: 421af47ff4a4
Revises: cd805f5ee0b0
Create Date: 2026-05-24 22:45:05.232933

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "421af47ff4a4"
down_revision: Union[str, Sequence[str], None] = "cd805f5ee0b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "restaurant_schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ru_id", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column(
            "meal_period",
            sa.Enum("LUNCH", "DINNER", name="meal_period_enum"),
            nullable=False,
        ),
        sa.Column("opens_at", sa.Time(), nullable=False),
        sa.Column("closes_at", sa.Time(), nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "weekday BETWEEN 0 AND 5", name="ck_weekday_between_0_and_5"
        ),
        sa.ForeignKeyConstraint(
            ["ru_id"],
            ["restaurants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ru_id", "weekday", "meal_period", name="uq_restaurant_schedule"
        ),
    )
    op.create_index(
        "ix_restaurant_schedule_lookup",
        "restaurant_schedules",
        ["ru_id", "weekday", "meal_period"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_restaurant_schedule_lookup", table_name="restaurant_schedules")
    op.drop_table("restaurant_schedules")
    # ### end Alembic commands ###
