"""create queue_snapshots table

Revision ID: 77b8a80e7339
Revises: d19530b9a7c9
Create Date: 2026-05-26 21:15:28.571222

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM as PgENUM

# revision identifiers, used by Alembic.
revision: str = "77b8a80e7339"
down_revision: Union[str, Sequence[str], None] = "d19530b9a7c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    existing_meal_period_enum = PgENUM(
        "LUNCH", "DINNER", name="meal_period_enum", create_type=False
    )
    op.create_table(
        "queue_snapshots",
        sa.Column("ru_id", sa.Integer(), nullable=False),
        sa.Column("meal_period", existing_meal_period_enum, nullable=False),
        sa.Column(
            "current_status",
            sa.Enum(
                "NO_QUEUE",
                "SMALL",
                "MEDIUM",
                "LARGE",
                "FOOD_ENDED",
                "NO_DATA",
                name="queue_snapshot_status_enum",
            ),
            server_default=sa.text("'NO_DATA'"),
            nullable=False,
        ),
        sa.Column(
            "reports_last_15m",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "confidence_score",
            sa.Numeric(precision=3, scale=2),
            server_default=sa.text("1.00"),
            nullable=False,
        ),
        sa.Column(
            "override_active",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("last_report_at", sa.DateTime(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "confidence_score >= 0.05 AND confidence_score <= 1.00",
            name="ck_confidence_score_between_0_05_and_1",
        ),
        sa.CheckConstraint(
            "reports_last_15m >= 0", name="ck_reports_last_15m_positive"
        ),
        sa.ForeignKeyConstraint(["ru_id"], ["restaurants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ru_id", "meal_period", name="pk_ru_id_meal_period"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("queue_snapshots")
    # ### end Alembic commands ###
