"""chore(timestamps): migrate to TIMESTAMPTZ

Revision ID: 8bd14aa6befa
Revises: 77b8a80e7339
Create Date: 2026-05-27 19:29:40.465432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8bd14aa6befa"
down_revision: Union[str, Sequence[str], None] = "77b8a80e7339"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Converts all TIMESTAMP columns to TIMESTAMPTZ.
    The USING clause explicitly interprets the existing naive values as UTC,
    which is what PostgreSQL's func.now() was already storing.
    """
    _tables_cols = [
        ("queue_reports", "created_at", False),
        ("queue_snapshots", "last_report_at", True),
        ("queue_snapshots", "updated_at", False),
        ("restaurant_schedule_exceptions", "created_at", False),
        ("restaurant_schedule_exceptions", "updated_at", False),
        ("restaurant_schedules", "created_at", False),
        ("restaurant_schedules", "updated_at", False),
        ("restaurants", "created_at", False),
        ("restaurants", "updated_at", False),
    ]
    for table, col, nullable in _tables_cols:
        op.alter_column(
            table,
            col,
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=nullable,
            postgresql_using=f"{col} AT TIME ZONE 'UTC'",
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "restaurants",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "restaurants",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "restaurant_schedules",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "restaurant_schedules",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "restaurant_schedule_exceptions",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "restaurant_schedule_exceptions",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "queue_snapshots",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "queue_snapshots",
        "last_report_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "queue_reports",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
