"""add public_id to restaurant_schedules

Revision ID: b9d7afa92f13
Revises: 421af47ff4a4
Create Date: 2026-05-24 23:11:00.597895

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9d7afa92f13"
down_revision: Union[str, Sequence[str], None] = "421af47ff4a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "restaurant_schedules", sa.Column("public_id", sa.Uuid(), nullable=False)
    )
    op.create_index(
        op.f("ix_restaurant_schedules_public_id"),
        "restaurant_schedules",
        ["public_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_restaurant_schedules_public_id"), table_name="restaurant_schedules"
    )
    op.drop_column("restaurant_schedules", "public_id")
    # ### end Alembic commands ###
