"""add unique constraint to campus

Revision ID: cd805f5ee0b0
Revises: 22032af4fdb4
Create Date: 2026-05-24 11:39:35.608248

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "cd805f5ee0b0"
down_revision: Union[str, Sequence[str], None] = "22032af4fdb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "restaurants", ["campus"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "restaurants", type_="unique")
    # ### end Alembic commands ###
