"""create queue_reports table

Revision ID: d19530b9a7c9
Revises: b9d7afa92f13
Create Date: 2026-05-25 08:34:37.787757

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM as PgENUM

# revision identifiers, used by Alembic.
revision: str = "d19530b9a7c9"
down_revision: Union[str, Sequence[str], None] = "b9d7afa92f13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    existing_meal_period_enum = PgENUM(
        "LUNCH", "DINNER", name="meal_period_enum", create_type=False
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queue_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.Uuid(), nullable=False),
        sa.Column("ru_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NO_QUEUE",
                "SMALL",
                "MEDIUM",
                "LARGE",
                "FOOD_ENDED",
                name="queue_report_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("meal_period", existing_meal_period_enum, nullable=False),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=False),
        sa.Column("accuracy_m", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column(
            "confidence_score",
            sa.Numeric(precision=3, scale=2),
            server_default=sa.text("1.00"),
            nullable=False,
        ),
        sa.Column(
            "is_mock_location",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "confidence_score BETWEEN 0.05 AND 1",
            name="ck_confidence_score_between_0_05_and_1",
        ),
        sa.ForeignKeyConstraint(["ru_id"], ["restaurants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_queue_reports_lookup",
        "queue_reports",
        ["ru_id", "meal_period", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_queue_reports_public_id"), "queue_reports", ["public_id"], unique=True
    )
    op.create_table(
        "restaurant_schedule_exceptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.Uuid(), nullable=False),
        sa.Column("ru_id", sa.Integer(), nullable=False),
        sa.Column("exception_date", sa.Date(), nullable=False),
        sa.Column(
            "exception_type",
            sa.Enum("CLOSED", "CUSTOM_HOURS", name="exception_type_enum"),
            nullable=False,
        ),
        sa.Column("meal_period", existing_meal_period_enum, nullable=True),
        sa.Column("opens_at", sa.Time(), nullable=True),
        sa.Column("closes_at", sa.Time(), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "opens_at IS NULL OR closes_at IS NULL OR opens_at < closes_at",
            name="ck_exception_opens_before_closes",
        ),
        sa.ForeignKeyConstraint(["ru_id"], ["restaurants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ru_id",
            "exception_date",
            "meal_period",
            name="uq_restaurant_schedule_exception",
        ),
    )
    op.create_index(
        op.f("ix_restaurant_schedule_exceptions_public_id"),
        "restaurant_schedule_exceptions",
        ["public_id"],
        unique=True,
    )
    op.create_index(
        "ix_schedule_exception_lookup",
        "restaurant_schedule_exceptions",
        ["ru_id", "exception_date"],
        unique=False,
    )
    op.create_index(
        "uq_restaurant_schedule_exception_whole_day",
        "restaurant_schedule_exceptions",
        ["ru_id", "exception_date"],
        unique=True,
        postgresql_where=sa.text("meal_period IS NULL"),
    )
    op.drop_constraint(
        op.f("restaurant_schedules_ru_id_fkey"),
        "restaurant_schedules",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "restaurant_schedules",
        "restaurants",
        ["ru_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "restaurant_schedules", type_="foreignkey")
    op.create_foreign_key(
        op.f("restaurant_schedules_ru_id_fkey"),
        "restaurant_schedules",
        "restaurants",
        ["ru_id"],
        ["id"],
    )
    op.drop_index(
        "uq_restaurant_schedule_exception_whole_day",
        table_name="restaurant_schedule_exceptions",
        postgresql_where=sa.text("meal_period IS NULL"),
    )
    op.drop_index(
        "ix_schedule_exception_lookup", table_name="restaurant_schedule_exceptions"
    )
    op.drop_index(
        op.f("ix_restaurant_schedule_exceptions_public_id"),
        table_name="restaurant_schedule_exceptions",
    )
    op.drop_table("restaurant_schedule_exceptions")
    op.drop_index(op.f("ix_queue_reports_public_id"), table_name="queue_reports")
    op.drop_index("ix_queue_reports_lookup", table_name="queue_reports")
    op.drop_table("queue_reports")
    # ### end Alembic commands ###
