"""add device_hash column to queue_reports

Revision ID: fb141e074154
Revises: 8bd14aa6befa
Create Date: 2026-06-04 15:47:22.000422

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb141e074154"
down_revision: Union[str, Sequence[str], None] = "8bd14aa6befa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "queue_reports", sa.Column("device_hash", sa.String(length=64), nullable=False)
    )
    op.create_index(
        "ix_queue_reports_lookup_device_hash",
        "queue_reports",
        ["device_hash", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_queue_reports_lookup_device_hash", table_name="queue_reports")
    op.drop_column("queue_reports", "device_hash")
    # ### end Alembic commands ###
