name: monitor-ru-dev

services:
  api:
    container_name: monitor-ru-api-dev
    image: monitor-ru-api:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: false
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      LOG_ENV: development
      REDIS_URL: redis://redis:6379/0
      CORS_ALLOWED_ORIGINS: '["*"]'
      CELERY_BROKER_URL: "amqp://admin:admin@rabbitmq:5672/"
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app/app
  

  celery-worker:
    container_name: monitor-ru-celery-worker-dev
    image: monitor-ru-api:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: false
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      LOG_ENV: development
      REDIS_URL: redis://redis:6379/0
      CORS_ALLOWED_ORIGINS: '["*"]'
      CELERY_BROKER_URL: "amqp://admin:admin@rabbitmq:5672/"
    depends_on:
      rabbitmq:
        condition: service_started
    command: celery -A app.core.celery:celery_app worker -l INFO
    volumes:
      - ../app:/app/app

  db:
    container_name: monitor-ru-db-dev
    image: postgres:17.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USER:-postgres}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-postgres}"
      POSTGRES_DB: "${DB_NAME:-mydb}"
      TEST_DB_NAME: "${TEST_DB_NAME:-test_db}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-mydb}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: monitor-ru-redis-dev
    image: redis:8.2-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test:
        - CMD
        - sh
        - -c
        - redis-cli ping || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
  
  rabbitmq:
    container_name: monitor-ru-rabbitmq-dev
    image: rabbitmq:3.13-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  node-exporter:
    image: prom/node-exporter:v1.11.1
    container_name: monitor-ru-node-exporter-dev
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    container_name: monitor-ru-prometheus-dev
    image: prom/prometheus:v3.6.0
    restart: unless-stopped
    depends_on:
      api:
        condition: service_started
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    extra_hosts:
    - "host.docker.internal:host-gateway"

  grafana:
    container_name: monitor-ru-grafana-dev
    image: grafana/grafana:12.2.0
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_started
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  grafana_data:
  prometheus_data:
