name: monitor-ru-dev

services:
  api:
    container_name: monitor-ru-api-dev
    image: monitor-ru-api:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: false
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      LOG_ENV: development
      REDIS_URL: redis://redis:6379/0
      CORS_ALLOWED_ORIGINS: '["*"]'
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app/app

  prometheus:
    image: prom/prometheus:v3.6.0
    restart: unless-stopped
    depends_on:
      api:
        condition: service_started
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:12.2.0
    restart: unless-stopped
    depends_on:
      prometheus:
        condition: service_started
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  db:
    container_name: monitor-ru-db-dev
    image: postgres:17.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USER:-postgres}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-postgres}"
      POSTGRES_DB: "${DB_NAME:-mydb}"
      TEST_DB_NAME: "${TEST_DB_NAME:-test_db}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-mydb}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: monitor-ru-redis-dev
    image: redis:8.2-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test:
        - CMD
        - sh
        - -c
        - redis-cli ping || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  postgres_data:
  redis_data:
  grafana_data:
  prometheus_data:
