name: CI

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #     - develop

  # pull_request:
  #   branches:
  #     - main
  #     - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DB_USER: ci
  DB_PASSWORD: ci
  DB_NAME: ci
  TEST_DB_NAME: ci_test
  DB_HOST: localhost
  DB_PORT: 5432
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  ADMIN_API_KEY: ci-admin-key
  APP_GEO_SECRET: ci-geo-secret
  PYTHON_VERSION: "3.14"

jobs:
  quality:
    name: Quality & Security
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --frozen --dev

      - name: Check formatting
        run: uv run ruff format --check app/

      - name: Run lint
        run: uv run ruff check app/

      - name: Run Bandit
        run: uv run bandit -r app -x app/core/seed_dev.py,app/tests

      - name: Run pip-audit
        run: uv run pip-audit --progress-spinner off

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: quality
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --frozen --dev

      - name: Run unit tests
        run: |
          COVERAGE_FILE=.coverage.unit \
          uv run pytest \
            app/tests/unit \
            -vv \
            -x \
            --disable-warnings \
            --cov=app \
            --cov-report= \
            --cov-fail-under=0

          mv .coverage.unit coverage-unit

      # O upload-artifact não funciona bem com arquivos ocultos .coverage, então movemos para um nome sem ponto antes de fazer o upload.
      - name: Upload unit coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: coverage-unit
          retention-days: 1

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs:
      - quality
      - unit-tests

    timeout-minutes: 15

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: ci
          POSTGRES_PASSWORD: ci
          POSTGRES_DB: ci_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ci -d ci_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --frozen --dev

      - name: Wait for PostgreSQL
        run: |
          until pg_isready \
            -h localhost \
            -p 5432 \
            -U ${{ env.DB_USER }} \
            -d ${{ env.TEST_DB_NAME }}
          do
            sleep 1
          done

      - name: Run integration tests
        run: |
          COVERAGE_FILE=.coverage.integration \
          uv run pytest \
            app/tests/integration \
            -vv \
            -x \
            --disable-warnings \
            --cov=app \
            --cov-report= \
            --cov-fail-under=0

          mv .coverage.integration coverage-integration

        # O upload-artifact não funciona bem com arquivos ocultos .coverage, então movemos para um nome sem ponto antes de fazer o upload.
      - name: Upload integration coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-integration
          path: coverage-integration
          retention-days: 1

  coverage:
    name: Coverage Validation
    runs-on: ubuntu-latest

    needs:
      - unit-tests
      - integration-tests

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - run: uv sync --frozen --dev

      - uses: actions/download-artifact@v4
        with:
          name: coverage-unit
          path: coverage-unit

      - uses: actions/download-artifact@v4
        with:
          name: coverage-integration
          path: coverage-integration

      - name: Combine coverage reports
        run: |
          cp coverage-unit/coverage-unit .coverage.unit
          cp coverage-integration/coverage-integration .coverage.integration

          uv run coverage combine \
            .coverage.unit \
            .coverage.integration

          uv run coverage report --fail-under=85
          uv run coverage xml

      - name: Upload final coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-final
          path: coverage.xml
          retention-days: 2
